### PR TITLE
fix: Maintaining the repository

### PR DESCRIPTION
**Pull request by SiddheshKanawade**
I have created this PR to keep a track of all the contributions for maintaining the repository. Following are some significant issues needed to be worked on:

- [x] management apis
- [ ] resolve enforcer(m, a)
- [ ] resolve abac policy input logic and enforce(params) error
- [ ] Upgrade tonic, prost and resolve error
- [ ] Reference and borrow errors in rpc_calls.rs

### CODE REVIEW

**Comment by SiddheshKanawade** [comment]
This is just a PR to have the track of commits to maintain the repository. The build fail to compile since there are lot more changes to be done. I am hunting them one by one and trying to resolve them

**Comment by hsluoyz** [comment]
@hackerchai

**Comment by hsluoyz** [comment]
@SiddheshKanawade any progress?

**Comment by SiddheshKanawade** [comment]
@hsluoyz I am on it, was inactive for last two weeks. I am looking forward to write RBAC tests first and then resolve the errors. For coming 2-3 days I will be inactive due to college reasons, after that I will be able to contribute to the repository.

**Comment by SiddheshKanawade** [comment]
This PR was opened long before, I had to switch to other tasks and hence was not able to contribute, hence closing this PR and opening a fresh one to keep better track of the changes.

**Comment by SiddheshKanawade** [comment]
Worked continued in #9

**Pull request closed without merging**
